### ISSUE TITLE
Could not compile `cdl-runner`

### ISSUE THREAD

**Issue by jmhirscher** [instructure/canvas-data-loader#12]
### Description ###

When I run cargo build --release, I am receiving the following error:

= note: liblibrocksdb_sys-4fe83a8a2d9f911a.rlib(env_win.o) : error LNK2019: unresolved external symbol __imp_PathIsRelativeA referenced in function "public: virtual class rocksdb::Status __cdecl rocksdb::port::WinEnvIO::GetAbsolutePath(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?GetAbsolutePath@WinEnvIO@port@rocksdb@@UEAA?AVStatus@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV56@@Z)
          C:\canvas-data-loader\target\release\deps\cdl_runner-7e809c944750d409.exe : fatal error LNK1120: 1 unresolved externals
          

error: aborting due to previous error

error: Could not compile `cdl-runner`.

### Additional Information ###

* Rust Version: rustc 1.30.1 (1433507eb 2018-11-07)
* Platform: Windows 7, SP1. I'm running VS 2017 with the C++ build tools.
* Logs: Attached is the output from running cargo build --release --verbose
[Build Output.txt](https://github.com/instructure/canvas-data-loader/files/2563806/Build.Output.txt)

**Comment by SecurityInsanity** [comment]
It sounds like this is a common problem with windows compiling tools. This should be fixed in the upstream library that we reach out to for rocksdb.

I'll be sure to file an issue upstream in the library that's causing this problem to ensure this project can be built on windows, but honestly even if it compiles CanvasDataLoader is tested only on Mac/Linux internally before we release new versions of this example. So if you could I'd highly recommend switching over to Linux/OSX.

**Comment by jmhirscher** [comment]
Good to know. The documentation lead me to believe it could be run on Windows, but I'll spin up a  Linux VM and see if I have better luck there.

**Comment by SecurityInsanity** [comment]
It absolutely should be able to be run on Windows, but bugs like this do pop up more frequently with Windows (windows native story code compiler doesn't have the best track record).

Anyway the issue has been filed in the upstream repo. When they fix it and cut a new release I'll bump our version, and it should work again.

**Comment by SecurityInsanity** [comment]
Hey,

Sorry about this! I forgot to close this issue, since it was fixed while I was out. This specific issue has been fixed. If you're running a stable rust, and windows 10 you should now be able to compile the code.
