### ISSUE TITLE
cdl_runner::db_client: insert error

### ISSUE THREAD

**Issue by latifatbraimah** [instructure/canvas-data-loader#13]
The biggest bottlenecks of the loader are really:

  * The fact we have to iterate through every record in order to determine if we need to delete a specific value.
  * The fact we don't batch together DELETEs/INSERTs at all.
  * The fact we're processing each table one at a time, without threading out.

All of these facts do slow it down considerably, and we've in the past avoided fixing these bottlenecks because we don't want people to rely on this full time working with Canvas Data. It's meant to be an example application showing users how to interact with the API, and how they could do things like "avoid historical refreshes".

We could one day down the road, fix these features, and turn the CDL into a fully supported solution, but that would have to be a product decision.

_Originally posted by @SecurityInsanity in https://github.com/instructure/canvas-data-loader/issues/6#issuecomment-427165092_

**Comment by SecurityInsanity** [comment]
Hey @latifatbraimah ,

As mentioned in the issue you're posting this from. This is a known bottleneck, and not one we plan on fixing for the reasons outlined in this comment. I'm unsure as to why exactly this was moved to it's own issue.

However, if you have any more questions I recommend posting them on the original issue (which is still open).

Thanks,
