### ISSUE TITLE
RUST_LOG=info is not recognized as an internal or external command

### ISSUE THREAD

**Issue by tolockuncp** [instructure/canvas-data-loader#15]
### Description ###

I have installed the Canvas-data-loader on a Windows 10 platform.

```
Version of rust
rustc 1.32.0 (9fda7c223 2019-01-16)
When I get to step 11 from the command prompt.
I have changed directories to canvas-data-loader-master
Everything compiled properly
Compiling librocksdb-sys v5.14.3
Compiling rocksdb v0.10.1
Compiling cdl-runner v0.4.0 (I:\CanvasData\canvas-data-loader-master)
Finished release [optimized] target(s) in 7m 00s
```

Is there something else that needs to be installed on a Windows machine?

### Additional Information ###

* Rust Version: rustc 1.32.0 (9fda7c223 2019-01-16)
* Platform: Windows 10
* Logs: None

**Comment by tolockuncp** [comment]
I have installed the Canvas-data-loader on a Windows 10 platform.
Version of rust
rustc 1.32.0 (9fda7c223 2019-01-16)
When I get to step 11 from the command prompt.
I have changed directories to canvas-data-loader-master\
Everything compiled properly
 Compiling librocksdb-sys v5.14.3
   Compiling rocksdb v0.10.1
   Compiling cdl-runner v0.4.0 (I:\CanvasData\canvas-data-loader-master)
    Finished release [optimized] target(s) in 7m 00s

Is there something else that needs to be installed on a Windows machine?

**Comment by SecurityInsanity** [comment]
Hello @tolockuncp ,

(Sorry about deleting your comment, was just cleaning it up so it's easier to read for future people running into the same problem). As for this error you're running into, it's actually a difference between linux & mac vs windows.

In linux/mac the command: `RUST_LOG=info ./target/release/canvas-data-loader` does two things:
   1. Set an environment variable "RUST_LOG" to the value "INFO" (for only that one command).
   2. Provide the actual command.

However windows doesn't look at it this way. Windows just looks at it all as one command. As such the easiest way to get this working is to just remove the: `RUST_LOG=info` bit, and just run the actual executable file itself (e.g. `./target/release/canvas-data-loader` / `./target/release/canvas-data-loader.exe` ). 

That being said you still probably want logs, so you can go manually set the environment variable rust log. [Here's a guide I found with a quick google search on how to set any environment variable](https://www.itechtics.com/create-custom-environment-variables-windows-10/). You'd want to create one with the variable: "RUST_LOG" and value "info" to get the same experience as running that command.
