### ISSUE TITLE
Issue with Windows Setup Rust PATH variable and Cargo Build

### ISSUE THREAD

**Issue by venkat5121** [instructure/canvas-data-loader#16]
### Description ###

I am following the steps in canvas [DOC-11943](https://community.canvaslms.com/docs/DOC-11943-how-to-use-the-canvas-data-cli-tool)
at Step 9, I can see that %USERPROFILE%\.cargo\bin is added to my Windows USER path instead of SYSTEM path.

next, I don't know what "to configure current shell run" mean. I blindly followed and executed source "%USERPROFILE%\.cargo\env" and it gave this error

```
'source' is not recognized as an internal or external command,
operable program or batch file.
```

probably there should be some window's way of doing it that I don't know.

at Step 10, I initially faced Virtual studio error and then I installed Build tools with C++ and now building release version it gave me following error

```
[2019-06-12T19:35:34Z INFO  cargo::core::compiler::job_queue] start: librocksdb-sys v5.18.3 => Target(script)/Profile() => Host
   Compiling librocksdb-sys v5.18.3
[2019-06-12T19:35:34Z INFO  cargo::core::compiler::job_queue] start: cookie_store v0.7.0 => Target(lib)/Profile(release) => Host
[2019-06-12T19:35:34Z INFO  cargo::core::compiler::job_queue] end: cookie_store v0.7.0 => Target(lib)/Profile(release) => Host
[2019-06-12T19:35:34Z INFO  cargo::core::compiler::job_queue] start: reqwest v0.9.18 => Target(lib)/Profile(release) => Host
[2019-06-12T19:35:34Z INFO  cargo::core::compiler::job_queue] end: reqwest v0.9.18 => Target(lib)/Profile(release) => Host
[2019-06-12T19:35:34Z INFO  cargo::core::compiler::job_queue] end: librocksdb-sys v5.18.3 => Target(script)/Profile() => Host
error: failed to run custom build command for `librocksdb-sys v5.18.3`
process didn't exit successfully: `C:\Softwares\CanvasDataLoader\canvas-data-loader\target\release\build\librocksdb-sys-10a20a9d59bb2f10\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'clang.dll\', \'libclang.dll\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', src\libcore\result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


C:\Softwares\CanvasDataLoader\canvas-data-loader>
```

I am not sure if I didn't do something right in step 9 which gave me this error in 10 or something else. but I am stuck and cannot move forward.

do I need to wait for successful completion of this step to see cdl-runner.bat/cdl-runner.exe file under my C:\Softwares\CanvasDataLoader\canvas-data-loader\target\release directory? 
because I am not seeing anything currently

### Additional Information ###

* Rust Version 

> rustc 1.35.0 (3c235d560 2019-05-20)

* Platform: 

> Windows 10 Desktop

*Logs: 

> Attached the cargo --build --verbose
[BuildOutput.txt](https://github.com/instructure/canvas-data-loader/files/3282939/BuildOutput.txt)

[community_link]: https://community.canvaslms.com/community/answers/data

**Comment by csunitdata** [comment]
The issue is resolved after installing LLVM.
I selected an option to create a system variable for all users while installing it.

I went through the next other steps successfully and my data is being loaded to the MySQL tables now (very slowly though). 

I am closing this issue.

**Comment by venkat5121** [comment]
The issue is resolved after installing LLVM.
I selected an option to create a system variable for all users while installing it.

I went through the next other steps successfully and my data is being loaded to the MySQL tables now (very slowly though).

I am closing this issue.
